server {
    listen 80;
    server_name 52.91.238.70;

    # Frontend Static Build
    location / {
        root /home/jay/InfraPilot/frontend/build;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Backend API
    location /api/ {
        include proxy_params;
        proxy_pass http://unix:/home/jay/InfraPilot/infrapilot.sock;
    }

    # Static files for Django (if any)
    location /static/ {
        alias /home/jay/InfraPilot/static/;
    }
}
