# Generated by Django 6.0.5 on 2026-05-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAILED', 'FAILED'), ('RUNNING', 'RUNNING')], default='RUNNING', max_length=20)),
                ('logs', models.TextField()),
                ('deployed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
