# Generated by Django 6.0.5 on 2026-05-07 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deployment',
            old_name='project_name',
            new_name='service',
        ),
    ]
