# Generated by Django 6.0.5 on 2026-05-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_project_name_deployment_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='commit_hash',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
